spring: 
    datasource:
        url: jdbc:mysql://localhost:3306/login?createDatabaseIfNotExist=true
        username: root
        password: 12345678

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    security:
        oauth2:
            client: 
                registration:
                    google:
                        client-id: 
                        client-secret: 
                    
    thymeleaf:
        cache: false